GET http://localhost:3000/users

###

GET http://localhost:3000/users/65c3593e0460a88d29e63e01

###

POST http://localhost:3000/users
Content-Type: application/json

{
	"name": "pepe"
}

###

DELETE http://localhost:3000/users/65c3593e0460a88d29e63e01

###

PATCH http://localhost:3000/users/65c3593e0460a88d29e63e01
Content-Type: application/json

{
	"name": "pepa"
}